trigger:
- none

pool:
  terta-pool

variables:
  bhavyapath: 'Enviroment\Pre-prod'

parameters:
- name: runInit
  type: boolean
  default: True

- name: runfmt
  type: boolean
  default: True

- name: runvalidate
  type: boolean
  default: True

- name: runplan
  type: boolean
  default: True

- name: runapply
  type: boolean
  default: False

steps:
- task: TerraformInstaller@1
  displayName: Terraform Install
  inputs:
   terraformVersion: 'latest'
    
- task: TerraformTask@5
  displayName: Terraform Init
  condition: eq('${{ parameters.runInit }}', true)
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(bhavyapath)'
    backendServiceArm: 'boom-sc'
    backendAzureRmOverrideSubscriptionID: 'fadfa500-48fa-4d7d-ae72-215103d56b2f'
    backendAzureRmResourceGroupName: 'rg-virus'
    backendAzureRmStorageAccountName: 'boomstorage4'
    backendAzureRmContainerName: 'viruscontainer'
    backendAzureRmKey: 'virus.tfstate'

- task: TerraformTask@5
  displayName: Terraform fmt
  condition: eq('${{ parameters.runfmt }}', true)
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(bhavyapath)'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'boom-sc'

- task: TerraformTask@5
  displayName: Terraform Validate
  condition: eq('${{ parameters.runvalidate }}', true)
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(bhavyapath)'

- task: TerraformTask@5
  displayName: Terraform Plan
  condition: eq('${{ parameters.runplan }}', true)
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(bhavyapath)'
    environmentServiceNameAzureRM: 'boom-sc'

- task: TerraformTask@5
  displayName: Terraform Apply
  condition: eq('${{ parameters.runapply }}', true)
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(bhavyapath)'
    environmentServiceNameAzureRM: 'boom-sc'


